[/]
current-settings-page=3
layout='/usr/share/onboard/layouts/Phone.onboard'
schema-version='2.3'
show-tooltips=true
system-theme-associations={'HighContrast': 'HighContrast', 'HighContrastInverse': 'HighContrastInverse', 'LowContrast': 'LowContrast', 'ContrastHighInverse': 'HighContrastInverse', 'Default': '', 'Arc HiDPI': '/home/kiosk/.local/share/onboard/themes/ShopnoOS.theme'}
theme='/home/kiosk/.local/share/onboard/themes/ShopnoOS.theme'
use-system-defaults=false
xembed-onboard=true

[auto-show]
enabled=true

[theme-settings]
background-gradient=50.0
color-scheme='/usr/share/onboard/themes/Black.colors'
key-fill-gradient=10.0
key-gradient-direction=0.0
key-label-font='Liberation Sans'
key-label-overrides=@as []
key-shadow-size=0.0
key-shadow-strength=0.0
key-size=100.0
key-stroke-gradient=32.0
key-stroke-width=100.0
key-style='flat'
roundrect-radius=5.0

[window]
docking-enabled=true
