#!/usr/bin/env bash

set -euo pipefail
# set -x

populate_apt_source() {
	cat << EOF > $CHROOT_DIR/etc/apt/sources.list
# See https://wiki.debian.org/SourcesList for more information.
deb http://deb.debian.org/debian trixie main contrib non-free-firmware
# deb-src http://deb.debian.org/debian trixie main contrib non-free-firmware

deb http://deb.debian.org/debian trixie-updates main contrib non-free-firmware
# deb-src http://deb.debian.org/debian trixie-updates main contrib non-free-firmware

deb http://security.debian.org/debian-security/ trixie-security main contrib non-free-firmware
# deb-src http://security.debian.org/debian-security/ trixie-security main contrib non-free-firmware

# Backports allow you to install newer versions of software made available for this release
deb http://deb.debian.org/debian trixie-backports main contrib non-free-firmware
# deb-src http://deb.debian.org/debian trixie-backports main contrib non-free-firmware
EOF
}

# populate_apt_source
