#!/usr/bin/env bash

set -euo pipefail
# set -x

populate_sudoers() {
	[[ -d $CHROOT_DIR/etc/sudoers.d/ ]] || mkdir -p $CHROOT_DIR/etc/sudoers.d

	cat << EOF > $CHROOT_DIR/etc/sudoers.d/pwfeedback
Defaults pwfeedback
EOF
}

# populate_sudoers

