dontChroot: false
timeout: 60
script:
  - command: "/usr/sbin/useradd -m -s /bin/bash -G sudo,netdev,plugdev,audio,video kiosk"
  - command: "/bin/sh -c 'echo kiosk:jadupc | chpasswd'"
  - command: "/usr/sbin/useradd -m -s /bin/bash -G sudo,netdev,plugdev,audio,video admin"
  - command: "/bin/sh -c 'echo admin:admin | chpasswd'"
  - command: "/usr/sbin/usermod -c \"Default User\" kiosk"
  - command: "/usr/sbin/usermod -c \"Admin\" admin"
  - command: "/usr/bin/dconf load /org/onboard/ < /etc/skel/.local/share/onboard/onboard.conf"

i18n:
  - name: "Creating users"

