---

userGroup:       users

defaultGroups:
    - cdrom
    - floppy
    - sudo
    - audio
    - dip
    - video
    - plugdev
    - netdev
    - lpadmin
    - scanner
    - bluetooth
    - dialout
    - uucp
    - adm

autologinGroup:		autologin
doAutologin:		false
sudoersGroup:		sudo
setRootPassword:	true
doReusePassword:	true
userShell: 			/bin/bash
